modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="testremote"
version="1.0.0"
displayName="TestRemote"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="FredLeon, MCreator"

[[dependencies.testremote]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



